### ISSUE TITLE
List all the points where people might want to contribute councillor information as they use PlanningAlerts

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/australian_local_councillors_popolo#122]
We think people who use PlanningAlerts are an important source of people who might contribute councillor information.

Currently this happens when they see their list of local councillors in the PlanningAlerts comment form, and they recognise them as being out of date. They email us to tell us the councillors are out of date. But if we don't have any councillors for them to write to yet (that would be out of date), then there is [no way for people to know](https://github.com/openaustralia/australian_local_councillors_popolo/issues/98#issuecomment-305383236) that they could be writing to their councillors—or that they might contribute information about them.

So, where are the moments in using PlanningAlerts that we might suggest to people that they could add councillors for their area? These are the potential points we're looking for. To keep the users motivation in mind, I think it's useful to describe these in a kind of story format:

e.g.

* After I've confirmed by comment to the local council, help me add local councillors for my area, so I can write to them.
* When I'm viewing applications in a PlanningAlerts email, let me know you're missing councillors for my area and help me add them, so other locals and I can start writing to them.

**Comment by equivalentideas** [comment]
@hisayohorie when you accept the invitation to join this repo as a collaborator, can you please assign this issue to you? 😀 

Some paths to discover some more points of entry from PlanningAlerts might be the commenting flow, signing up for alerts, contributing scraper data, etc. . Think about what the people who are real passionate about PlanningAlerts are up to.

**Comment by hisayohorie** [comment]
Here are the chart of the potential entry points. Ones in bold are the picks for the first iteration
[entry_point_chart.docx](https://github.com/openaustralia/australian_local_councillors_popolo/files/1073392/entry_point_chart.docx)

**Comment by hisayohorie** [comment]
Here is the chart for possible entry points in PlanningAlerts for people to make contribution. Ones in bold are the pick for the first iteration.
[entry_point_chart.pdf](https://github.com/openaustralia/australian_local_councillors_popolo/files/1073411/entry_point_chart.pdf)

**Comment by hisayohorie** [comment]
Here is the chart for possible entry points in PlanningAlerts for people to make contribution. Ones in bold are the pick for the first iteration.
<embed src="https://github.com/openaustralia/australian_local_councillors_popolo/files/1073419/entry_point_chart.docx">

**Comment by hisayohorie** [comment]
![91fce65d2553401ce8321c6d8aa7e0e0-0](https://user-images.githubusercontent.com/12241881/27114408-7040abce-5091-11e7-88d3-0055bb91e0da.png)

**Comment by hisayohorie** [comment]
Here is the chart of possible entry points in PlanningAlerts for the contributor. Bolds are the picks for the first iteration
https://github.com/openaustralia/australian_local_councillors_popolo/files/1073419/entry_point_chart.docx
![91fce65d2553401ce8321c6d8aa7e0e0-1](https://user-images.githubusercontent.com/12241881/27114431-9c1d772c-5091-11e7-8add-291e0b11dab0.png)

**Comment by hisayohorie** [comment]
Here is the chart of possible entry points in PlanningAlerts for the contributor. Bolds are the picks for the first iteration
![91fce65d2553401ce8321c6d8aa7e0e0-0](https://user-images.githubusercontent.com/12241881/27114435-ac3fb44e-5091-11e7-89b4-ad20ac34cbf2.png)
![91fce65d2553401ce8321c6d8aa7e0e0-1](https://user-images.githubusercontent.com/12241881/27114439-b47d13ea-5091-11e7-98fb-687de9c6dba7.png)

**Comment by equivalentideas** [comment]
@hisayohorie nice work 👌 I think we've got lots of good options from your list and the two in the comment description. I'll close this issue and we can use this when we're implementing that flow from using PlanningAlerts to contributing councillor information 🎸
