### ISSUE TITLE
The Councillor’s page on the council website should be recorded as the `source`

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/australian_local_councillors_popolo#2]
In Popolo how should we capture a councillor’s page on the council website? Do we want this in here at all?

It's useful to have in the spreadsheet as the source of the info and the place we can get more/update from—but do we want it in here?

Currently [we've called it there 'website'](https://github.com/openaustralia/australian_local_councillors_popolo/blob/master/victorian_local_councillor_popolo.json#L8-L12):

```
{
      "email": "katef@alpineshire.vic.gov.au",
      "id": "alpine_shire_council/kate_farrell",
      "image": "http://www.alpineshire.vic.gov.au/Page/Images/Cr_Farrell_Feb_2015_web.jpg",
      "name": "Kate Farrell",
      "links": [
        {
          "url": "http://www.alpineshire.vic.gov.au/Page/Page.aspx?Page_Id=58",
          "note": "website"
        }
      ],
      "images": [
        {
          "url": "http://www.alpineshire.vic.gov.au/Page/Images/Cr_Farrell_Feb_2015_web.jpg"
        }
      ]
    }
```

**Comment by henare** [comment]
I definitely think the source is useful.

We captured it in the [Ukraine data](https://morph.io/openaustralia/ukraine_verkhovna_rada_deputies) as `source_url` and I thought EveryPolitician was using that but it appears not.

`website` does seem a little misleading. If changing it to `source` is easy then let's do that.

**Comment by equivalentideas** [comment]
> If changing it to source is easy then let's do that.

That sounds perfect.

We should change the column name in the Google Spreadsheet from `url` then re-convert it.

**Comment by henare** [comment]
I think this is done.
