### ISSUE TITLE
Add councillor data from Moreton Bay, Snowy River Armidale North Sydney and Randwick

### ISSUE THREAD

**Issue by kat** [openaustralia/australian_local_councillors_popolo#37]
updated [spreadsheet](https://docs.google.com/spreadsheets/d/1_Ea99E5yXnHXW62o_lRo9khdbccEWfttpy2tyuYZYOE/edit#gid=1381284966_) with Moreton Bay, Snowy River Albury and Armidale

Just updated including party information from latest council elections in 2012 for Armidale from the [AEC's local election results](http://www.pastvtr.elections.nsw.gov.au/LGE2012/lge-index.htm)

**Comment by kat** [comment]
Where there's no party affiliation given at AEC I've entered 'unassigned' rather than leave blank.

**Comment by equivalentideas** [comment]
* [x] Moreton Bay
* [ ] Snowy River
* [ ] Albury
* [ ] Armidale

**Comment by equivalentideas** [comment]
> Where there's no party affiliation given at AEC I've entered 'unassigned' rather than leave blank.

So far we've been leaving it blank if there's no information for them, because “unaligned” is also a thing that some people specify. I think that could get really confusing so I recon it's a better approach for now to leave it blank. Do mind removing “unassigned” from the ones where there was no information @kat ?

**Comment by kat** [comment]
ok will do

**Comment by kat** [comment]
that was only for Armidale btw/

**Comment by equivalentideas** [comment]
> that was only for Armidale btw

Sweet 👍  can you post in here when it's done and I'll update the json.

**Comment by kat** [comment]
Done.

**Comment by kat** [comment]
just added another NSW.

**Comment by equivalentideas** [comment]
I've extracted the individual councils into #48 #49 #50 closing this issue
