### ISSUE TITLE
Add all the current data used in PlanningAlerts to the spreadsheets

### ISSUE THREAD

**Issue by henare** [openaustralia/australian_local_councillors_popolo#4]
We currently have image URLs for all councillors in PA. If we start using this data we lose that because it's not in here. We should add it.

**Comment by equivalentideas** [comment]
This is a great point @henare . I've just updated this to cover all the data, emails for example, because the same point applies.

The councils are:

* [ ] Marrickville
* [ ] Toowoomba
* [ ] Boroondara City
