### ISSUE TITLE
Load Randwick Councillors into WriteIt

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/australian_local_councillors_popolo#72]
For some reason this council is no being imported into WriteIt when you refresh the 'data source' at the moment. I can't tell why.

**Comment by henare** [comment]
I can see Randwick councillors in WriteIt so this might be fixed http://planningalerts.writeit.ciudadanointeligente.org/en/manage/settings/api/

**Comment by henare** [comment]
It looks good to me so I've enabled it.

**Comment by henare** [comment]
Eugh. It appears that a person showing up there doesn't necessarily mean they're contactable.

I can't use the WriteIt front-end to contact an example councillor from this list so I've disabled it again.

**Comment by equivalentideas** [comment]
> I can't use the WriteIt front-end to contact an example councillor from this list so I've disabled it again.

We've got this as a [step in the readme](https://github.com/openaustralia/planningalerts/blob/master/README.md#adding-councillors-for-an-authority) , but it's tacked onto to the end of a sentence, not very obvious.

> If you're using WriteIt then the next step is to refresh the data source in WriteIt so it knows about the coucillors you've added to the popolo data. Check that your refresh was successful by confirming that you now have the option to write to your newly added councillors in the WriteIt frontend.

I see you've made [a suggestion on the WriteIt repo](https://github.com/ciudadanointeligente/write-it/issues/1157) that could help us check for this so we don't have to be computers 💻  If we can check this in the load process somehow that would be way better 👍

**Comment by henare** [comment]
>We've got this as a step in the readme , but it's tacked onto to the end of a sentence, not very obvious

@equivalentideas I think you missed your original error report above. It's not a problem of refreshing the data source:

>For some reason this council is no being imported into WriteIt when you refresh the 'data source' at the moment. I can't tell why.

I think this is affected by https://github.com/ciudadanointeligente/write-it/issues/983#issuecomment-228683603

**Comment by equivalentideas** [comment]
> @equivalentideas I think you missed your original error report above.

Sorry, the readme is meant to communication that it's the actually WriteIt frontend that needs to be checked, not the api. But from this I'd say it's not clear enough ;-)

> I can see Randwick councillors in WriteIt so this might be fixed http://planningalerts.writeit.ciudadanointeligente.org/en/manage/settings/api/

Really we should be checking if they show up here: http://planningalerts.writeit.ciudadanointeligente.org/en/write/who/

If you're suggestion to have some indication that they aren't contactable in the API gets included, or non-contactable people aren't included, that would mean we could automate this step.

Am I understanding this correctly?

**Comment by henare** [comment]
@equivalentideas I'm sorry but I don't understand what you're saying. I think the problem may be that what you're describing is something that's not directly about this issue. If that's the case maybe a helpful thing to do would be to open a new issue and discuss that there?

**Comment by equivalentideas** [comment]
>  I think the problem may be that what you're describing is something that's not directly about this issue.

Totally. I think I can see the improvement to the PlanningAlerts readme that needs to be made.

**Comment by henare** [comment]
This is all fixed now so I've re-enabled write to councillors for Randwick :+1:
