### ISSUE TITLE
Load Ryde Councillors into WriteIt

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/australian_local_councillors_popolo#75]
Problem loading them into WriteIt for some reason. Could be related to reemergence of https://github.com/ciudadanointeligente/write-it/issues/983

**Comment by henare** [comment]
Hmm, all except the last person (`city_of_ryde/jane_stott`) seem to be loaded now.

**Comment by henare** [comment]
Loaded and working! https://twitter.com/PlanningAlerts/status/859594344277229568 I had to remove [one person that has retired](http://www.dailytelegraph.com.au/newslocal/northern-district-times/rydes-craig-chung-resigns-after-being-elected-to-city-of-sydney-council/news-story/eacdf513013140cc0adbbfdfbddb673f).
