### ISSUE TITLE
Brisbane City Council

### ISSUE THREAD

**Issue by archoo** [openaustralia/australian_local_councillors_popolo#85]
data is in the spreadsheet.. 

got past a ruby ssl error, but rake exec still fails with a malformed CSV error.. raw file looks fine to me, guessing its something in the popolo json_to_csv code.. i'll get this process working eventually :)

**Comment by equivalentideas** [comment]
Thanks @archoo I did find some merged cells in the sheet yesterday. Could it be worth stripping back the formatting and trying again? Up to you :)

**Comment by archoo** [comment]
finally got the code working locally.. i'm sorely tempted to rewrite the lot in python.. ruby on windows is not fun..  PR #86 should now be ok..

**Comment by equivalentideas** [comment]
Closed by #86
